### ISSUE TITLE
In String, Out Int

### ISSUE THREAD

**Issue by Piwington** [ONSdigital/es-enrichment-sg#18]
Mike and myself noticed that when responder_id and enterprise_ref arrive in enrichment it is a string but somewhere in the process they are turned into integers.

This is an issue because some responder_id values and possible enterprise_ref can start with a leading 0 and this will be lost on conversion to int.

**Comment by thomashenson** [comment]
- responder_id: String
- enterprise_ref: String

**Comment by thomashenson** [comment]
Think this could be resolved now if you'se would like to check? 😄 @kingmushroom @Piwington
